default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  url: <%= ENV.fetch("QUEUE_DATABASE_URL", "postgres://localhost/yourapp_development") %>
  <<: *default

test:
  url: <%= ENV.fetch("QUEUE_DATABASE_URL", "postgres://localhost/yourapp_test") %>
  <<: *default

production:
  url: <%= ENV.fetch("QUEUE_DATABASE_URL", ENV["DATABASE_URL"]) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  <<: *default
